language: node_js
node_js:
  - '6'
  - '5'
  - '4'
  - 'node'

before_install:
  - 'npm install -g npm@latest'

install:
  - 'npm install'

notifications:
  email:
    on_success: never
    on_failure: change
